[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mfai"
authors = [
  {name="Frank Guibert", email="frank.guibert@meteo.fr"},
  {name="Theo Tournier", email="theo.tournier@meteo.fr"},
  {name="Lea Berthomier", email="lea.berthomier@meteo.fr"},
  {name="Bruno Pradel", email="bruno.pradel@meteo.fr"},
]
description = "Meteo-France's Artificial Intelligence Python Package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies", "version"]
license = {file = "LICENSE"}
keywords = ["PyTorch", "Deep Learning", "Artificial Intelligence", "Meteo-France"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools_scm]

[project.urls]
Homepage = "https://github.com/meteofrance/mfai"

[tool.mypy]
# [mypy configuration file doc](https://mypy.readthedocs.io/en/stable/config_file.html#config-file-format)
# [Import discovery](https://mypy.readthedocs.io/en/stable/command_line.html#import-discovery)
ignore_missing_imports = true

# [Platform configuration](https://mypy.readthedocs.io/en/stable/command_line.html#platform-configuration)
python_version = "3.11"

# [Disallow dynamic typing](https://mypy.readthedocs.io/en/stable/command_line.html#disallow-dynamic-typing)
disallow_any_decorated = true
disallow_any_expr = true
disallow_any_generics = true

# [Untyped definitions and calls](https://mypy.readthedocs.io/en/stable/command_line.html#untyped-definitions-and-calls)
disallow_untyped_defs = true
disallow_untyped_decorators = true

# [None and Optional handling](https://mypy.readthedocs.io/en/stable/command_line.html#none-and-optional-handling)
implicit_optional = true

# [Configuring warnings](https://mypy.readthedocs.io/en/stable/command_line.html#configuring-warnings)
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

# [Miscellaneous strictness flags](https://mypy.readthedocs.io/en/stable/command_line.html#miscellaneous-strictness-flags)
strict_equality = true

# [Configuring error messages](https://mypy.readthedocs.io/en/stable/command_line.html#configuring-error-messages)
show_error_context = true
show_error_code_links = true
show_error_codes = true
pretty = true
force_uppercase_builtins = true
force_union_syntax = true


exclude = [
  '^mfai/config/*$',
  '^mfai/tokenizer/*$',
  '^mfai/torch/*$',
  '^mfai/tokenizers.py$',
]