# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    env:
      PYTHONPATH: '.'
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Lint with ruff
      run: |
        ruff format --check .
        ruff check . --select I
    - name: Gather Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          *.py
          **/*.py
    - name: Type hinting with mypy on changed files
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: |
        mypy ${{ steps.changed-py-files.outputs.all_changed_files }}
    - name: Test with pytest
      run: |
        pytest --cov=mfai --cov-fail-under=85 tests/